[package]
name = "sync-dotfiles-rs"
version = "0.1.2"
edition = "2021"
authors = ["Utsav Balar <utsavbalar1231@gmail.com>"]
description = "Sync dotfiles across machines"


[dependencies]
anyhow = "1.0"
ron = "0.8"
home = "0.5"
crypto-hash = "0.3"
walkdir = "2"

[dependencies.serde]
version = "1"
features = ["derive"]
